chatterbot = Project.new(title: "ChatterBot", description: "A no code solution to creating your own ChatBot powered by ChatGPT. I specifically want to create this for my Mum so that she could save time and automate her customer service.", github_link: 'https://github.com/georgekettle/chatterbot-market', image_url: "chatterbot.svg")
chatterbot.technology_list.add("React Native", "Ruby on Rails")
chatterbot.save!

ruby_docs = Project.new(title: "Ruby Docs", description: "Frustrated with the poor design of the current ruby documentation, I set out to redesign the ruby docs with beginner devs in mind.", link: "https://www.ruby-docs.org", github_link: "https://github.com/georgekettle/ruby-docs", image_url: "rubydocs.svg", open_source: true)
ruby_docs.technology_list.add("Ruby on Rails")
ruby_docs.save!

align_body = Project.new(title: "Align Body", description: "Started an online Pilates business with Co-founder. We created a rails app and displayed this inside a React native app to make the app more convenient for users.", github_link: "https://github.com/georgekettle/align-body", image_url: "alignbody.svg")
align_body.technology_list.add("React Native", "Ruby on Rails")
align_body.save!

hubbbi = Project.new(title: "Hubbbi", description: "An app to help entrepreneurs and business owners to create online communities and courses. It's essentially a course builder with a community focus.", github_link: "https://github.com/georgekettle/hubbbi", image_url: "hubbbi.svg")
hubbbi.technology_list.add("React Native", "Ruby on Rails")
hubbbi.save!

work = Work.create([
  { role_title: "Full Stack Developer / Teacher", company: "Le Wagon", company_img: "lewagon.svg", start_year: "2020", end_year: "Present", description: "Lead Teacher at Le Wagon Melbourne and other campuses worldwide. This is a 10 week intensive bootcamp where I am responsible for giving lectures on topics including Ruby, Rails, HTML, CSS, JS, Heroku deployment and other topics including background jobs, search, web- sockets, testing and hotwire.js features. I am also responsible for helping students implementing and deploying projects, leading teams and resolving team disputes." },
  { role_title: "Co-founder & CTO", company: "The Farm Folk", company_img: "the_farm_folk.svg", start_year: "2019", end_year: "2020", description: "I built a fullstack rails application for local & organic vegie box subscriptions. This project was hosted on Heroku and utilised Stripe billing API's to create recurring payments for users." },
  { role_title: "Co-founder & CTO", company: "Align Body", company_img: "align_body.svg", start_year: "2021", end_year: "2021", description: "Created an online pilates app that was deployed to and distributed on the Android and iOS app store. The app was a creative solution employing a simple react native app to host a rails web app through a native WebView component. Consistencies in design were maintained through JS communication between the two. The native app was deployed using expo EAS services, whilst the web app was deployed on Heroku and utilised Vimeo private video hosting, Stripe for subscriptions an Tailwindcss for styling." },
  { role_title: "Co-founder & CTO", company: "Hubbbi", company_img: "hubbbi.svg", start_year: "2021", end_year: "2021", description: "Created an online course building app with a pilot group to guide development. Hubbbi was designed to help teachers & leaders publish course content whilst also building community. The app was built in Rails with a Postgresql db, hosted on Heroku, styled with Tailwindcss and heavily implemented JS functionalities like drag and drop page editor with rich text, image uploads and recursive page design (like a computer file system)." },
  { role_title: "Social Media Marketing", company: "Farm&Co", company_img: "farm_and_co.svg", start_year: "2016", end_year: "2019", description: "I built a fullstack rails application for local & organic vegie box subscriptions. This project was hosted on Heroku and utilised Stripe billing API's to create recurring payments for users." }
])

education = Education.create([
  { title: "Fullstack coding bootcamp", company: "Le Wagon", company_img: "lewagon.svg", start_year: "2018", link: "https://www.lewagon.com" },
  { title: "Graphic design bootcamp", company: "Shillington", company_img: "shillington.svg", start_year: "2016", link: "https://www.shillingtoneducation.com/" },
  { title: "Business/Finance Degree", company: "QUT", company_img: "qut.svg", start_year: "2017", link: "https://www.qut.edu.au/" },
  { title: "Medicine Degree", company: "UNSW", company_img: "unsw.svg", start_year: "2014", link: "https://www.unsw.edu.au/" }
])

quotes = Quote.create([
  { source: "Batch 988 (Melbourne)", content: 'Great guy with a great attitude. Brings joy and life to the class with his sense of humour.' },
  { source: "Batch 988 (Melbourne)", content: 'Technical: The Best Presentation: The Best Problem-solving: The Best I have an issue with my project and no one could solve it but this guy George helped me. We spent lots of time on it and We fixed it. George is very good.' },
  { source: "Batch 988 (Melbourne)", content: 'Excellent teacher and communicator, extremely knowledgeable about Rails, good at being able to quickly work through unfamiliar codebases and understand any questions we might ask of him.' },
  { source: "Batch 988 (Melbourne)", content: 'He is one of my favourite teachers. A really patient teacher knows very well how to explain the code.' },
  { source: "Batch 988 (Melbourne)", content: 'George was very friendly, always with a smile and appreciated his sense of humour. Super knowledgable with his technical skills and problem solving. Gave some really good advice and insights especially on the final project.' },
  { source: "Batch 1044 (Melbourne)", content: 'george was amazing! truly the standout amongst the teachers in terms of technical knowledge. he really has a passion for coding and has so much expertise!' },
  { source: "Batch 1044 (Melbourne)", content: 'george always brought good energy to the lectures and always had answers for my tickets nothing bad to say about him' },
  { source: "Batch 1044 (Melbourne)", content: "Absolutely amazing teacher. So relaxed and incredibly intelligent, helpful and patient. Great at explaining simple or complex code. Give the man a raise!! It would be a great loss to Le Wagon if George ever left, I'm so thankful he was so involved with our batch." },
  { source: "Batch 1044 (Melbourne)", content: "Great guy! Very, very strong developer & teacher - helped a lot & you see how he loves to explore new stuff like Turbo…loved that he showed this and the power of it to us! Little sad that we had no chance to meet in person though :)" },
  { source: "Batch 1044 (Melbourne)", content: 'George needs to get a pay rise, he is seriously the best teacher you have. It would not have been possible to do my final project without him' },
  { source: "Batch 1044 (Melbourne)", content: "My favourite teacher at Lewagon. He has a very vast knowledge which I assume he has gained through practical usage. He identifies the problem in our code at first sight and he explains everything very clear and simple manner. I really like the way he approaches the problem step-by-step. It can only be expected from a well-experienced person." },
  { source: "Batch 1044 (Melbourne)", content: 'Wonderful instructor that did a great job at explaining the subject matter very well.' },
  { source: "Batch 1044 (Melbourne)", content: "George is a legend. I think he embodies what everyone wants to be in the next 5 years. I can't speak more highly of him. He listens he understands and make the presentations awesome. Areas for improvement is that he moves quickly. This isn't because he lacks awareness its because he has a lot to get through in about an hour and half. Students who are a little slower to understand concepts get lost easily. My suggestion would be to break up long lectures. Morning and after-lunch lectures. He goes off on a tangent when he's ready but that's because he's super excited. But if it wasn't for those tangent moments, we wouldn't know about turbo, hotwire, tailwind, and other important concepts which make our job easier. But honestly, George is a legend. Hard to find any negatives about him." },
  { source: "Batch 1044 (Melbourne)", content: "George is a genius, he is genuine, and smart, I felt some of the lectures we went back and forth changing things quickly and removing things rather than focusing on deeper explanations of what was happening which led to some confusion when learning some things for only one or two days but I feel that was mainly due to time constraints of the lectures. But whenever we were stuck in projects, He always had the answer. Would love to have worked with him in person and pick his brain a little more. He was always supportive positive. Thanks George" },
  { source: "Batch 1044 (Melbourne)", content: "George was excellent, 11/10." },
  { source: "Batch 1044 (Melbourne)", content: "Amazing teacher, super supportive and positive no matter the general feeling of the class. No complaints." },
  { source: "Batch 1044 (Melbourne)", content: "11/10 Very engaging and passionate as a teacher - really appreciated how George would work the code based on our inputs instead of just copy and pasting from LeWagon. His deep understanding of the fundamentals also allowed him to explain concepts to us very clearly. You can tell he really enjoys software engineering. Really funny guy so was easy to build rapport in and out of lectures. He was really good at problem-solving skills, being able to resolve our issues quickly or even suggest alternative solutions. Went above and beyond a lot." },
  { source: "Batch 1044 (Melbourne)", content: "George was such a great teacher, he had the ability to jump onto any ticket (no matter how complicated) and would normally have the solution within a couple of mins which was amazing! Super helpful and so thankful for him helping out on many occasions! He also showed us loads of libraries and other front end tools which was cool (and great to save for later). Only thing was he was usually the only person that could help on those areas so it meant all of those tickets had to go to George. The queue for him in the project weeks was always 1+ hours long, which meant you were stuck for longer than you might have if others could help with it. The other thing I would say is some of the lectures went so fast, would be nice to slow down a little - although a lot of the lectures George covered were the more complex issues where a lot of content had to be covered in one day. Overall legend of a teacher though!" },
  { source: "Batch 1044 (Melbourne)", content: "A very relaxed teacher and extremely comforting attitude which compliments his teaching style. He taught one of the hardest weeks in our batch and helped each one of us with an understanding on DB's." },
  { source: "Batch 986 (Europe)", content: "My favourite TA. Super thorough knowledge of rails. Was very good at debugging tools and out of box diagnostic skills." },
  { source: "Batch 986 (Europe)", content: "Very friendly and positive. Excited for the group ideas, always ready to help." },
  { source: "Batch 986 (Europe)", content: "George was great and super approachable" },
  { source: "Batch 986 (Europe)", content: "Only was in a couple of lectures with him. Everything was pretty ok. He explained everything with a good pace and left space for questions. He had a really good vibe." },
  { source: "Batch 986 (Europe)", content: "Very passionate and enthusiastic. It's a shame George only joined us towards the end. He made his mark!" },
  { source: "Batch 986 (Europe)", content: "He solved problems really quick." },
  { source: "Batch 986 (Europe)", content: "George was great. In the one ticket I had he knew the answer but also explained the answer to me which I appreciated" },
  { source: "Batch 986 (Europe)", content: "Unfortunately I haven't had the chance to get to know George very well, but he was always really helpful and positive in our tickets, and when he was checking in for our group projects!" },
  { source: "Batch 986 (Europe)", content: "I had really few tickets with George but the interaction with him was really satisfing. He is a very knowledgeable dev. I really enjoyed his live code and wished he was more involve in our batch." },
  { source: "Batch 977 (Madrid)", content: "Really helpful during SQL week, with clear explanations during lectures and tickets" },
  { source: "Batch 977 (Madrid)", content: "Very competent in the technical related categories and has clean presentation skills. I cant point anything negative or to be improved, so keep the good job going and thx mate!" },
  { source: "Batch 977 (Madrid)", content: "I liked how he explained some really complicated concepts, but making you enjoy it!" },
  { source: "Batch 977 (Madrid)", content: "I really enjoyed George's lectures, how he taught made sense to me and he had a good energy." },
  { source: "Batch 977 (Madrid)", content: "George was also very good with tickets. No complaints." },
  { source: "Batch 990 (Europe)", content: "George was a great teacher, really down do earth, patient and knowledgable. He was constantly on time and in a great mood. 11/10" },
  { source: "Batch 990 (Europe)", content: "Great guy, he should definitely stick with it. I have no suggestions for improvement because everything is already very good. Keep it up!" },
  { source: "Batch 990 (Europe)", content: "George was an amazing TA and lecturer. He really helped a lot with making concepts clear and always took time to make sure you understood a concept before letting you leave the ticket. No weaknesses!" },
  { source: "Batch 990 (Europe)", content: "he is super nice, always willing to help" },
  { source: "Batch 990 (Europe)", content: "An Excellent teacher overall. Concise and clear. He has an AMAZING, WONDERFUL and ENTHUSIASTIC attitude, keeping things light without loosing on commitment. Very knowledgeable and confident teacher. A 10/10 teacher for me. You are TOP!" },
  { source: "Batch 990 (Europe)", content: "Amazing teacher and mentor for our group! He was very calm and patient, very relaxed and always gave the feeling that there are no stupid questions. Also, he seemed to have extensive technical experience and was always able to help." },
  { source: "Batch 990 (Europe)", content: "George is an absolute powerhouse of a teacher, knows how to engage students in a way that helps them pay attention and even if they're not paying attention is able to summarize complicated topics in a simple and slow concise way to help even the least focused students understand. Without George I don't know if I would have been able to understand as much as I did and most likely would not have been able to complete the course. He gave me strength on days when I wanted to give up and helped bring a smile to all our faces when it was obvious we were worn out from all the info. I could say more but I think he knows we truly 'loved' him. Be well mate!" },
  { source: "Batch 990 (Europe)", content: "Awesome developer. Very nice with all of us. Great skills explaining, but sometimes need to be kind of slow with advanced concepts." },
  { source: "Batch 990 (Europe)", content: "He was on topic, very skilled. Could quickly fix the problem" },
  { source: "Batch 990 (Europe)", content: "George is a legend. He is kind, patient, entertaining, very helpful, genuine and knows his code! Me maybe moved a little fast in lecture sometimes but that's all ." },
  { source: "Batch 990 (Europe)", content: "It was an awesome teacher as he takes the time to explain things and get you to think about the issues and ways to solve it . Nothing bad to say about him." },
  { source: "Batch 990 (Europe)", content: "I have been able to see the strengths of each teacher and in your case you have a very valuable one, you know how to read how we are in each moment and change the dynamics of the lecture or the live code. I have given some trainings and this, when you are doing it from a distance, is difficult. in one of your readings, the live code was easier than the challenge, but I don't remember which one, if I find a comment in slack I'll let you know. to solve the tickets, when the problem is not developed you don't provide the direct answer, you give us the necessary information, which is much more valuable so I have to put 5starts ! if you fancy a surfing or skateboarding trip to the Canary Islands here you have a home :) in exchange for some extra coding lessons :)" },
  { source: "Batch 990 (Europe)", content: "Amazing, thank you for everything George! Very clear and engaging during the lectures, and was quick to help me with any problems in the tickets." },
  { source: "Batch 990 (Europe)", content: "George was awesome, not a bad thing i can say about him, You keep rocking G-man" },
  { source: "Batch 990 (Europe)", content: "George was brilliant. Any ideas we had during out product weeks he fully got behind and helped us try and figure them out. He was very motivating and I really enjoyed having his as a TA. His problem-solving skills where amazing and he got really interested in what we were trying to do, giving hints and ideas of how to approach a certain problem. One of, if not, my favourite TAs." },
  { source: "Batch 990 (Europe)", content: "For me George was the one of the best teacher. He was so kind and open to help in any way, I think I'm gonna remember for a long time (I love to start a day with music) thank you for all George." },
  { source: "Batch 990 (Europe)", content: "Very impressed with George. Great at explaining and I enjoy when I had a ticket with him. Brings great energy too!" },
  { source: "Batch 990 (Europe)", content: "Experienced developer, learned a lot, always ready to help, good lectures, friendly... Great TA" },
  { source: "Batch 990 (Europe)", content: "George was one of my favourite teachers. His subject knowledge is excellent and his attitude, teaching style, and temperament create a relaxed but disciplined and challenging learning environment." },
  { source: "Batch 990 (Europe)", content: "Strengths: patient, clear explanations, easy-going, super friendly, encouraging" },
  { source: "Batch 990 (Europe)", content: "George is funny and makes the lectures engaging. I remember he sat with me for almost 40 minutes trying to help me understand one of the well easy concepts now but difficult back then. I think he has good technical skills. Sometimes though, he does go fast during the lectures but I think that it applies to every lecturer espeically when its a big topic. He has great problem solving skills and I've never had any issues during tickets with him and even in the lectures if there is some problem with the code, he will find it quickly and explain what he did wrong." },
  { source: "Batch 990 (Europe)", content: "George is a very competent teacher and he really knows what is doing, he can explain things in a clear way and he is a very nice and sympathetic person! Maybe sometime he goes a bit fast, but I think it understandable because he is a fast thinker, my only suggestions is to go a bit slower a repeat concepts more, because there are students, that are new to the topics of the bootcamp." },
  { source: "Batch 990 (Europe)", content: "I FOUND GEORGE A VERY ENGAGING TEACHER, AND VERY EASY TO FOLLOW IN HIS CLASSES. GEORGE WHEN HELPING THE CHALLENGES, GUIDES YOU WELL IN ORDER FOR YOU TO UNDERSTAND, INSTEAD OF TAKING THE EASY ROAD AND JUST GIVING YOU THE ANSWER. I MUST SAY I HAD LEARNT A LOT AND HOW TO TACKLE PROBLEMS." },
  { source: "Batch 990 (Europe)", content: "Very knowledgeable and very much got everyone in the mood for learning with morning music!" },
  { source: "Batch 990 (Europe)", content: "He was very friendly and easy to ask any questions. I felt that he gave me always right suggestions and advice that's why I asked many times. Also, his reboot was great. it gave me a big chance to understand MVC well. In addition, he always leaves us today's lesson codes on his github. This is immensely helpful." },
  { source: "Batch 990 (Europe)", content: "George allies friendliness, great attitude and skill. During lectures he obviously cared about being understood and seemed to know exactly what he was talking about. During project weeks he was for me and many others a certainty that your ticket would help you advance. Big plus for Le Wagon, he is obviously a Ruby lover ;)" },
  { source: "Batch 990 (Europe)", content: "Any lesson with George was very good. He interacted a lot with us and nobody slept. Probably the best teacher we had." },
])

# Create blogs
Blog.create([
  {
    title: "How to create a ChatBot with ChatGPT and React Native",
    content: "I recently created a ChatBot app using React Native and ChatGPT. I wanted to create this for my Mum so that she could save time and automate her customer service. I also wanted to create this for myself so that I could learn more about ChatGPT and how to integrate it with React Native. I also wanted to learn more about how to create a React Native app from scratch. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things. I also wanted to learn more about how to integrate ChatGPT with React Native. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things.",
  },
  {
    title: "How to create a ChatBot with ChatGPT and React Native",
    content: "I recently created a ChatBot app using React Native and ChatGPT. I wanted to create this for my Mum so that she could save time and automate her customer service. I also wanted to create this for myself so that I could learn more about ChatGPT and how to integrate it with React Native. I also wanted to learn more about how to create a React Native app from scratch. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things. I also wanted to learn more about how to integrate ChatGPT with React Native. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things.",
  },
  {
    title: "How to create a ChatBot with ChatGPT and React Native",
    content: "I recently created a ChatBot app using React Native and ChatGPT. I wanted to create this for my Mum so that she could save time and automate her customer service. I also wanted to create this for myself so that I could learn more about ChatGPT and how to integrate it with React Native. I also wanted to learn more about how to create a React Native app from scratch. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things. I also wanted to learn more about how to integrate ChatGPT with React Native. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things.",
  },
  {
    title: "How to create a ChatBot with ChatGPT and React Native",
    content: "I recently created a ChatBot app using React Native and ChatGPT. I wanted to create this for my Mum so that she could save time and automate her customer service. I also wanted to create this for myself so that I could learn more about ChatGPT and how to integrate it with React Native. I also wanted to learn more about how to create a React Native app from scratch. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things. I also wanted to learn more about how to integrate ChatGPT with React Native. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things.",
  },
  {
    title: "How to create a ChatBot with ChatGPT and React Native",
    content: "I recently created a ChatBot app using React Native and ChatGPT. I wanted to create this for my Mum so that she could save time and automate her customer service. I also wanted to create this for myself so that I could learn more about ChatGPT and how to integrate it with React Native. I also wanted to learn more about how to create a React Native app from scratch. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things. I also wanted to learn more about how to integrate ChatGPT with React Native. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things.",
  },
  {
    title: "How to create a ChatBot with ChatGPT and React Native",
    content: "I recently created a ChatBot app using React Native and ChatGPT. I wanted to create this for my Mum so that she could save time and automate her customer service. I also wanted to create this for myself so that I could learn more about ChatGPT and how to integrate it with React Native. I also wanted to learn more about how to create a React Native app from scratch. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things. I also wanted to learn more about how to integrate ChatGPT with React Native. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things.",
  },
  {
    title: "How to create a ChatBot with ChatGPT and React Native",
    content: "I recently created a ChatBot app using React Native and ChatGPT. I wanted to create this for my Mum so that she could save time and automate her customer service. I also wanted to create this for myself so that I could learn more about ChatGPT and how to integrate it with React Native. I also wanted to learn more about how to create a React Native app from scratch. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things. I also wanted to learn more about how to integrate ChatGPT with React Native. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things.",
  },
  {
    title: "How to create a ChatBot with ChatGPT and React Native",
    content: "I recently created a ChatBot app using React Native and ChatGPT. I wanted to create this for my Mum so that she could save time and automate her customer service. I also wanted to create this for myself so that I could learn more about ChatGPT and how to integrate it with React Native. I also wanted to learn more about how to create a React Native app from scratch. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things. I also wanted to learn more about how to integrate ChatGPT with React Native. I have created a few React Native apps before, but I have always used Expo to create them. This time I wanted to create a React Native app from scratch so that I could learn more about the native side of things.",
  },
])